### ISSUE TITLE
Template

### ISSUE THREAD

**Issue by osCMattiFinn** [phundament/app#172]
This has a bug in the backend template.

When the page has enough content an extra scroll bar displays.

A main container must have a fixed height with overflow:auto set.

This looks and feels very bad.

**Comment by schmunk42** [comment]
This is related to:
- https://github.com/dmstr/yii2-adminlte-asset/issues/14
- https://github.com/dmstr/yii2-adminlte-asset/issues/24

...and will be fixed with the next release which contains AdminLTE v2.
Note: If you upgrade existing projects to AdminLTE v2, you very likely have to adjust the views in the admin/backend module.
