### ISSUE TITLE
Error when access: sh: 1: lessc: not found

### ISSUE THREAD

**Issue by trexanhvn** [phundament/app#190]
I installed phundament with newest version. But when I access, error apeared like this:

    AssetConverter command 'lessc '/vagrant/mysite/cms/web/assets/2f9dc4d1/less/app.less' '/vagrant/mysite/cms/web/assets/2f9dc4d1/less/app.css' --no-color --source-map' failed with exit code 127:
    STDOUT:

    STDERR:
    sh: 1: lessc: not found

I don't know how to fix it? Any idea for this?

**Comment by sum1190** [comment]
What OS do you use?

**Comment by schmunk42** [comment]
In general, I'd recommend using `docker`, since all pieces are in place there (less was a main reason for us to switch to the dockerized approach btw).

But if can or do not want to use `docker`, you can also install [nodejs/npm](https://github.com/phundament/docker-images/blob/master/phundament/php-one/5.6-7.0/Dockerfile-5.6-fpm#L29) to your Vagrant VM and then [less](https://github.com/phundament/docker-images/blob/master/phundament/php-one/5.6-7.0/Dockerfile-5.6-fpm#L58).

A workaround would be to "downgrade" to CSS files, you could pick them from:

- https://github.com/phundament/app/blob/4.0.0-rc8/src/assets/AppAsset.php#L22
- https://github.com/phundament/app/blob/4.0.0-rc8/src/assets/web/css/app.css

**Comment by trexanhvn** [comment]
I fixed this error. B/c my VM (Ubuntu Trusty) didn't installed `lessc` package.
I've used docker, but have some problems that I don't know. So I moved to use composer.

I will use `docker` again and will post errors if it happen.

Thanks all.

**Comment by schmunk42** [comment]
> I've used docker, but have some problems that I don't know.

@trexanhvn Would be really interested in your problems and error messages, if you've the time create new issues, thank you!
